### PR TITLE
Remove backward compatibility

### LINKED ISSUE #70: Remove findFile and findFileAsync
Remove the exports or `findFile()` and `findFileAsync()` kept in for backwards compatibility.

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes #70

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/atom-linter/73)

### CODE REVIEW

**Comment by SpainTrain** [comment]
:ok_hand:

**Comment by Arcanemagus** [comment]
Go for it :wink:.

**Comment by steelbrain** [comment]
:ship: ing

**Comment by steelbrain** [comment]
Published :tada:

**Pull request merged**
