### PR TITLE
Fix reference to undefined object `cleanupCallback`

### PR DESCRIPTION
**Pull request by SpainTrain**
See discussion at https://github.com/AtomLinter/atom-linter/pull/39

Needed for https://github.com/AtomLinter/linter-pylint/pull/55

### CODE REVIEW

**Comment by steelbrain** [comment]
LGTM. Thanks!

**Comment by SpainTrain** [comment]
cool, if this gets published to npm I can pick it up in linter-pylint

**Comment by steelbrain** [comment]
Doing that right now

**Comment by SpainTrain** [comment]
:heart:

**Comment by steelbrain** [comment]
Done.

**Pull request merged**
