### PR TITLE
Check if column start is greater than line length

### PR DESCRIPTION
**Pull request by albertosantini**
Add a control to rangeFromLineNumber, checking if colStart is a value greater than the length of the line.

See https://github.com/AtomLinter/linter-eslint/issues/276

### CODE REVIEW

**Comment by steelbrain** [comment]
Can you please document this in CHANGELOG under the `Upcoming` title?

**Comment by steelbrain** [comment]
Also some specs for it would be nice, I'll try to fix the problem in existing specs and you can then pull master in

**Comment by albertosantini** [comment]
Do you prefer I close this PR and create a new one, squashing the commits and forking again from the master (3.3.5)?

**Comment by steelbrain** [comment]
Sure

**Pull request closed without merging**
