### PR TITLE
Repo maintenance

### PR DESCRIPTION
**Pull request by Arcanemagus**
# Overhaul of the repository aspect

The main aspects of this PR are:

-   [x] Adding `ucompiler` configuration
-   [x] Add `eslint` config.
-   [x] Move the specs to ES6
-   [x] Fix the specs on Windows
-   [ ] Update CI config

## `ucompiler` configuration

Although `babel` transpilation support was in there already, this adds the
ability to do `npm run watch` to have constant rebuilds of the code while
working on it. It also seems the `babel` version had _two_ blank lines at the
end, which this fixes.

## `eslint` config

How this didn't exist until now is beyond me, but here is where it starts
apparently :stuck_out_tongue:. Fixing the linting issues exposed by this
involves refactoring a few of the functions, and in general should result in
cleaner code.

## Move the specs to ES6

Let's get rid of the last vestiges of CoffeeScript :stuck_out_tongue:.

## Fix the specs on Windows

Currently running `npm test` on Windows results in a _lot_ of errors, we should
have passing specs regardless of the OS!

## Update CI config

Currently we are only building on the OS X containers on Travis-CI, and not in
an optimal manner even on there. The CI builds will look like this when
finished:

-   Travis-CI: Atom Stable + Beta, on both Linux and OS X
-   AppVeyor: Atom Stable on Windows
-   CircleCI: If we want an alternative Linux image to test as well.

**NOT READY - DO NOT MERGE!**

### CODE REVIEW

**Comment by steelbrain** [comment]
[This is what I get on ubuntu](https://gist.github.com/steelbrain/d76550096512a4fbecac)

**Comment by Arcanemagus** [comment]
Fixed `rangeFromLinNumber`, looking into `findAsync`.

**Comment by Arcanemagus** [comment]
The `cat.exe` comes from here: http://unxutils.sourceforge.net/

**Comment by steelbrain** [comment]
I've reviewed the code and it Looks Good to Me and should work

**Comment by steelbrain** [comment]
I've reviewed the code about and it Looks Good To Me and should work

**Comment by Arcanemagus** [comment]
CI is apparently ignoring some uncaught errors on *NIX, investigating.

**Comment by Arcanemagus** [comment]
Huh, can't reproduce this locally. As everything seems to be working properly I'm merging this :grinning:.

**Pull request merged**
