### PR TITLE
Import helpers from linter

### PR DESCRIPTION
**Pull request by steelbrain**
Just like the title says

### CODE REVIEW

**Comment by steelbrain** [comment]
How do we write tests in this repo, pure Jasmine?
/cc @AtomLinter/linter

**Comment by iam4x** [comment]
@steelbrain Yeah simple Jasmine or mocha tests should do the job :+1:

**Comment by steelbrain** [comment]
I figured that we can run atom specs even when it's not a package. so I am sticking with it.

**Comment by steelbrain** [comment]
Merging as the tests pass
(and because waiting for reviews is boring)

**Pull request merged**
